package javaapplication5;

public class RutaGUI extends javax.swing.JPanel {

    /** Creates new form Celda */
    public RutaGUI() {
        initComponents();
    }

    public int getLeftDistance() {
        return Integer.valueOf(spinLeft.getValue() + "");
    }

    public int getTopDistance() {
        return Integer.parseInt(spinTop.getValue() + "");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        spinTop = new javax.swing.JSpinner();
        spinLeft = new javax.swing.JSpinner();

        jLabel4.setText("jLabel4");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinTop.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        add(spinTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, -1));

        spinLeft.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        add(spinLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 40, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinLeft;
    private javax.swing.JSpinner spinTop;
    // End of variables declaration//GEN-END:variables
}
