/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AsistenciaAlumnos.java
 *
 * Created on Feb 1, 2009, 5:25:27 PM
 */

package prototypes;

/**
 *
 * @author rCuser
 */
public class AsistenciaAlumnos extends javax.swing.JFrame {

    /** Creates new form AsistenciaAlumnos */
    public AsistenciaAlumnos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox81 = new javax.swing.JCheckBox();
        jCheckBox80 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox82 = new javax.swing.JCheckBox();
        jCheckBox83 = new javax.swing.JCheckBox();
        jCheckBox84 = new javax.swing.JCheckBox();
        jCheckBox85 = new javax.swing.JCheckBox();
        jCheckBox86 = new javax.swing.JCheckBox();
        jCheckBox87 = new javax.swing.JCheckBox();
        jCheckBox88 = new javax.swing.JCheckBox();
        jCheckBox89 = new javax.swing.JCheckBox();
        jCheckBox90 = new javax.swing.JCheckBox();
        jCheckBox91 = new javax.swing.JCheckBox();
        jCheckBox92 = new javax.swing.JCheckBox();
        jCheckBox93 = new javax.swing.JCheckBox();
        jCheckBox94 = new javax.swing.JCheckBox();
        jCheckBox95 = new javax.swing.JCheckBox();
        jCheckBox96 = new javax.swing.JCheckBox();
        jCheckBox97 = new javax.swing.JCheckBox();
        jCheckBox98 = new javax.swing.JCheckBox();
        jCheckBox99 = new javax.swing.JCheckBox();
        jCheckBox100 = new javax.swing.JCheckBox();
        jCheckBox101 = new javax.swing.JCheckBox();
        jCheckBox102 = new javax.swing.JCheckBox();
        jCheckBox103 = new javax.swing.JCheckBox();
        jCheckBox104 = new javax.swing.JCheckBox();
        jCheckBox105 = new javax.swing.JCheckBox();
        jCheckBox106 = new javax.swing.JCheckBox();
        jCheckBox107 = new javax.swing.JCheckBox();
        jCheckBox108 = new javax.swing.JCheckBox();
        jCheckBox109 = new javax.swing.JCheckBox();
        jCheckBox110 = new javax.swing.JCheckBox();
        jCheckBox111 = new javax.swing.JCheckBox();
        jCheckBox112 = new javax.swing.JCheckBox();
        jCheckBox113 = new javax.swing.JCheckBox();
        jCheckBox114 = new javax.swing.JCheckBox();
        jCheckBox115 = new javax.swing.JCheckBox();
        jCheckBox116 = new javax.swing.JCheckBox();
        jCheckBox117 = new javax.swing.JCheckBox();
        jCheckBox118 = new javax.swing.JCheckBox();
        jCheckBox119 = new javax.swing.JCheckBox();
        jCheckBox120 = new javax.swing.JCheckBox();
        jCheckBox121 = new javax.swing.JCheckBox();
        jCheckBox122 = new javax.swing.JCheckBox();
        jCheckBox123 = new javax.swing.JCheckBox();
        jCheckBox124 = new javax.swing.JCheckBox();
        jCheckBox125 = new javax.swing.JCheckBox();
        jCheckBox126 = new javax.swing.JCheckBox();
        jCheckBox127 = new javax.swing.JCheckBox();
        jCheckBox128 = new javax.swing.JCheckBox();
        jCheckBox129 = new javax.swing.JCheckBox();
        jCheckBox130 = new javax.swing.JCheckBox();
        jCheckBox131 = new javax.swing.JCheckBox();
        jCheckBox132 = new javax.swing.JCheckBox();
        jCheckBox133 = new javax.swing.JCheckBox();
        jCheckBox134 = new javax.swing.JCheckBox();
        jCheckBox135 = new javax.swing.JCheckBox();
        jCheckBox136 = new javax.swing.JCheckBox();
        jCheckBox137 = new javax.swing.JCheckBox();
        jCheckBox138 = new javax.swing.JCheckBox();
        jCheckBox139 = new javax.swing.JCheckBox();
        jCheckBox140 = new javax.swing.JCheckBox();
        jCheckBox141 = new javax.swing.JCheckBox();
        jCheckBox142 = new javax.swing.JCheckBox();
        jCheckBox143 = new javax.swing.JCheckBox();
        jCheckBox144 = new javax.swing.JCheckBox();
        jCheckBox145 = new javax.swing.JCheckBox();
        jCheckBox146 = new javax.swing.JCheckBox();
        jCheckBox147 = new javax.swing.JCheckBox();
        jCheckBox148 = new javax.swing.JCheckBox();
        jCheckBox149 = new javax.swing.JCheckBox();
        jCheckBox150 = new javax.swing.JCheckBox();
        jCheckBox151 = new javax.swing.JCheckBox();
        jCheckBox152 = new javax.swing.JCheckBox();
        jCheckBox153 = new javax.swing.JCheckBox();
        jCheckBox154 = new javax.swing.JCheckBox();
        jCheckBox155 = new javax.swing.JCheckBox();
        jCheckBox156 = new javax.swing.JCheckBox();
        jCheckBox157 = new javax.swing.JCheckBox();
        jCheckBox158 = new javax.swing.JCheckBox();
        jCheckBox159 = new javax.swing.JCheckBox();
        jCheckBox160 = new javax.swing.JCheckBox();
        jCheckBox161 = new javax.swing.JCheckBox();
        jCheckBox162 = new javax.swing.JCheckBox();
        jCheckBox163 = new javax.swing.JCheckBox();
        jCheckBox164 = new javax.swing.JCheckBox();
        jCheckBox165 = new javax.swing.JCheckBox();
        jCheckBox166 = new javax.swing.JCheckBox();
        jCheckBox167 = new javax.swing.JCheckBox();
        jCheckBox168 = new javax.swing.JCheckBox();
        jCheckBox169 = new javax.swing.JCheckBox();
        jCheckBox170 = new javax.swing.JCheckBox();
        jCheckBox171 = new javax.swing.JCheckBox();
        jCheckBox172 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField84 = new javax.swing.JTextField();
        jTextField152 = new javax.swing.JTextField();
        jTextField153 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTextField1.setBackground(new java.awt.Color(153, 204, 255));
        jTextField1.setText("Alumno");

        jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("SESIONES");

        jPanel2.setEnabled(false);
        jPanel2.setLayout(new java.awt.GridLayout(10, 18, 1, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("1");
        jPanel2.add(jLabel10);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("2");
        jPanel2.add(jLabel12);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("3");
        jPanel2.add(jLabel14);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("4");
        jPanel2.add(jLabel22);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("5");
        jPanel2.add(jLabel23);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("6");
        jPanel2.add(jLabel24);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("7");
        jPanel2.add(jLabel25);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("8");
        jPanel2.add(jLabel26);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("9");
        jPanel2.add(jLabel27);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("10");
        jPanel2.add(jLabel28);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("11");
        jPanel2.add(jLabel29);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("12");
        jPanel2.add(jLabel30);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("13");
        jPanel2.add(jLabel31);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("14");
        jPanel2.add(jLabel32);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("15");
        jPanel2.add(jLabel33);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("16");
        jPanel2.add(jLabel34);

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("17");
        jPanel2.add(jLabel35);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("18");
        jPanel2.add(jLabel36);

        jCheckBox11.setSelected(true);
        jCheckBox11.setEnabled(false);
        jPanel2.add(jCheckBox11);

        jCheckBox12.setSelected(true);
        jCheckBox12.setEnabled(false);
        jPanel2.add(jCheckBox12);

        jCheckBox13.setSelected(true);
        jCheckBox13.setEnabled(false);
        jPanel2.add(jCheckBox13);

        jCheckBox14.setSelected(true);
        jCheckBox14.setEnabled(false);
        jPanel2.add(jCheckBox14);

        jCheckBox15.setSelected(true);
        jCheckBox15.setEnabled(false);
        jPanel2.add(jCheckBox15);

        jCheckBox16.setSelected(true);
        jCheckBox16.setEnabled(false);
        jPanel2.add(jCheckBox16);

        jCheckBox17.setSelected(true);
        jCheckBox17.setEnabled(false);
        jPanel2.add(jCheckBox17);

        jCheckBox18.setSelected(true);
        jCheckBox18.setEnabled(false);
        jPanel2.add(jCheckBox18);

        jCheckBox19.setSelected(true);
        jCheckBox19.setEnabled(false);
        jPanel2.add(jCheckBox19);

        jCheckBox20.setSelected(true);
        jCheckBox20.setEnabled(false);
        jPanel2.add(jCheckBox20);

        jCheckBox21.setSelected(true);
        jCheckBox21.setEnabled(false);
        jPanel2.add(jCheckBox21);

        jCheckBox22.setSelected(true);
        jCheckBox22.setEnabled(false);
        jPanel2.add(jCheckBox22);

        jCheckBox23.setSelected(true);
        jCheckBox23.setEnabled(false);
        jPanel2.add(jCheckBox23);

        jCheckBox24.setSelected(true);
        jCheckBox24.setEnabled(false);
        jPanel2.add(jCheckBox24);

        jCheckBox25.setSelected(true);
        jCheckBox25.setEnabled(false);
        jPanel2.add(jCheckBox25);

        jCheckBox26.setSelected(true);
        jCheckBox26.setEnabled(false);
        jPanel2.add(jCheckBox26);

        jCheckBox27.setSelected(true);
        jCheckBox27.setEnabled(false);
        jPanel2.add(jCheckBox27);

        jCheckBox28.setSelected(true);
        jCheckBox28.setEnabled(false);
        jPanel2.add(jCheckBox28);

        jCheckBox29.setSelected(true);
        jCheckBox29.setEnabled(false);
        jPanel2.add(jCheckBox29);

        jCheckBox30.setSelected(true);
        jCheckBox30.setEnabled(false);
        jPanel2.add(jCheckBox30);

        jCheckBox31.setSelected(true);
        jCheckBox31.setEnabled(false);
        jPanel2.add(jCheckBox31);

        jCheckBox32.setSelected(true);
        jCheckBox32.setEnabled(false);
        jPanel2.add(jCheckBox32);

        jCheckBox33.setSelected(true);
        jCheckBox33.setEnabled(false);
        jPanel2.add(jCheckBox33);

        jCheckBox34.setSelected(true);
        jCheckBox34.setEnabled(false);
        jPanel2.add(jCheckBox34);

        jCheckBox35.setSelected(true);
        jCheckBox35.setEnabled(false);
        jPanel2.add(jCheckBox35);

        jCheckBox36.setSelected(true);
        jCheckBox36.setEnabled(false);
        jPanel2.add(jCheckBox36);

        jCheckBox37.setSelected(true);
        jCheckBox37.setEnabled(false);
        jPanel2.add(jCheckBox37);

        jCheckBox38.setSelected(true);
        jCheckBox38.setEnabled(false);
        jPanel2.add(jCheckBox38);

        jCheckBox39.setSelected(true);
        jCheckBox39.setEnabled(false);
        jPanel2.add(jCheckBox39);

        jCheckBox40.setSelected(true);
        jCheckBox40.setEnabled(false);
        jPanel2.add(jCheckBox40);

        jCheckBox41.setSelected(true);
        jCheckBox41.setEnabled(false);
        jPanel2.add(jCheckBox41);

        jCheckBox42.setSelected(true);
        jCheckBox42.setEnabled(false);
        jPanel2.add(jCheckBox42);

        jCheckBox43.setSelected(true);
        jCheckBox43.setEnabled(false);
        jPanel2.add(jCheckBox43);

        jCheckBox44.setEnabled(false);
        jPanel2.add(jCheckBox44);

        jCheckBox45.setEnabled(false);
        jPanel2.add(jCheckBox45);

        jCheckBox46.setEnabled(false);
        jPanel2.add(jCheckBox46);

        jCheckBox47.setEnabled(false);
        jPanel2.add(jCheckBox47);

        jCheckBox48.setSelected(true);
        jCheckBox48.setEnabled(false);
        jPanel2.add(jCheckBox48);

        jCheckBox49.setSelected(true);
        jCheckBox49.setEnabled(false);
        jPanel2.add(jCheckBox49);

        jCheckBox50.setSelected(true);
        jCheckBox50.setEnabled(false);
        jPanel2.add(jCheckBox50);

        jCheckBox51.setSelected(true);
        jCheckBox51.setEnabled(false);
        jPanel2.add(jCheckBox51);

        jCheckBox52.setSelected(true);
        jCheckBox52.setEnabled(false);
        jPanel2.add(jCheckBox52);

        jCheckBox53.setSelected(true);
        jCheckBox53.setEnabled(false);
        jPanel2.add(jCheckBox53);

        jCheckBox54.setSelected(true);
        jCheckBox54.setEnabled(false);
        jPanel2.add(jCheckBox54);

        jCheckBox55.setSelected(true);
        jCheckBox55.setEnabled(false);
        jPanel2.add(jCheckBox55);

        jCheckBox56.setSelected(true);
        jCheckBox56.setEnabled(false);
        jPanel2.add(jCheckBox56);

        jCheckBox57.setSelected(true);
        jCheckBox57.setEnabled(false);
        jPanel2.add(jCheckBox57);

        jCheckBox58.setSelected(true);
        jCheckBox58.setEnabled(false);
        jPanel2.add(jCheckBox58);

        jCheckBox59.setSelected(true);
        jCheckBox59.setEnabled(false);
        jPanel2.add(jCheckBox59);

        jCheckBox60.setSelected(true);
        jCheckBox60.setEnabled(false);
        jPanel2.add(jCheckBox60);

        jCheckBox61.setSelected(true);
        jCheckBox61.setEnabled(false);
        jPanel2.add(jCheckBox61);

        jCheckBox62.setSelected(true);
        jCheckBox62.setEnabled(false);
        jPanel2.add(jCheckBox62);

        jCheckBox63.setEnabled(false);
        jPanel2.add(jCheckBox63);

        jCheckBox64.setEnabled(false);
        jPanel2.add(jCheckBox64);

        jCheckBox65.setEnabled(false);
        jPanel2.add(jCheckBox65);

        jCheckBox66.setSelected(true);
        jCheckBox66.setEnabled(false);
        jPanel2.add(jCheckBox66);

        jCheckBox67.setSelected(true);
        jCheckBox67.setEnabled(false);
        jPanel2.add(jCheckBox67);

        jCheckBox68.setSelected(true);
        jCheckBox68.setEnabled(false);
        jPanel2.add(jCheckBox68);

        jCheckBox69.setSelected(true);
        jCheckBox69.setEnabled(false);
        jPanel2.add(jCheckBox69);

        jCheckBox70.setSelected(true);
        jCheckBox70.setEnabled(false);
        jPanel2.add(jCheckBox70);

        jCheckBox71.setSelected(true);
        jCheckBox71.setEnabled(false);
        jPanel2.add(jCheckBox71);

        jCheckBox72.setSelected(true);
        jCheckBox72.setEnabled(false);
        jPanel2.add(jCheckBox72);

        jCheckBox73.setSelected(true);
        jCheckBox73.setEnabled(false);
        jPanel2.add(jCheckBox73);

        jCheckBox74.setSelected(true);
        jCheckBox74.setEnabled(false);
        jPanel2.add(jCheckBox74);

        jCheckBox75.setSelected(true);
        jCheckBox75.setEnabled(false);
        jPanel2.add(jCheckBox75);

        jCheckBox76.setSelected(true);
        jCheckBox76.setEnabled(false);
        jPanel2.add(jCheckBox76);

        jCheckBox77.setSelected(true);
        jCheckBox77.setEnabled(false);
        jPanel2.add(jCheckBox77);

        jCheckBox81.setSelected(true);
        jCheckBox81.setEnabled(false);
        jPanel2.add(jCheckBox81);

        jCheckBox80.setSelected(true);
        jCheckBox80.setEnabled(false);
        jPanel2.add(jCheckBox80);

        jCheckBox79.setSelected(true);
        jCheckBox79.setEnabled(false);
        jPanel2.add(jCheckBox79);

        jCheckBox78.setSelected(true);
        jCheckBox78.setEnabled(false);
        jPanel2.add(jCheckBox78);

        jCheckBox82.setEnabled(false);
        jPanel2.add(jCheckBox82);

        jCheckBox83.setSelected(true);
        jCheckBox83.setEnabled(false);
        jPanel2.add(jCheckBox83);

        jCheckBox84.setSelected(true);
        jCheckBox84.setEnabled(false);
        jPanel2.add(jCheckBox84);

        jCheckBox85.setSelected(true);
        jCheckBox85.setEnabled(false);
        jPanel2.add(jCheckBox85);

        jCheckBox86.setEnabled(false);
        jPanel2.add(jCheckBox86);

        jCheckBox87.setEnabled(false);
        jPanel2.add(jCheckBox87);

        jCheckBox88.setEnabled(false);
        jPanel2.add(jCheckBox88);

        jCheckBox89.setSelected(true);
        jCheckBox89.setEnabled(false);
        jPanel2.add(jCheckBox89);

        jCheckBox90.setSelected(true);
        jCheckBox90.setEnabled(false);
        jPanel2.add(jCheckBox90);

        jCheckBox91.setSelected(true);
        jCheckBox91.setEnabled(false);
        jPanel2.add(jCheckBox91);

        jCheckBox92.setSelected(true);
        jCheckBox92.setEnabled(false);
        jPanel2.add(jCheckBox92);

        jCheckBox93.setSelected(true);
        jCheckBox93.setEnabled(false);
        jPanel2.add(jCheckBox93);

        jCheckBox94.setSelected(true);
        jCheckBox94.setEnabled(false);
        jPanel2.add(jCheckBox94);

        jCheckBox95.setSelected(true);
        jCheckBox95.setEnabled(false);
        jPanel2.add(jCheckBox95);

        jCheckBox96.setSelected(true);
        jCheckBox96.setEnabled(false);
        jPanel2.add(jCheckBox96);

        jCheckBox97.setSelected(true);
        jCheckBox97.setEnabled(false);
        jPanel2.add(jCheckBox97);

        jCheckBox98.setSelected(true);
        jCheckBox98.setEnabled(false);
        jPanel2.add(jCheckBox98);

        jCheckBox99.setSelected(true);
        jCheckBox99.setEnabled(false);
        jPanel2.add(jCheckBox99);

        jCheckBox100.setSelected(true);
        jCheckBox100.setEnabled(false);
        jPanel2.add(jCheckBox100);

        jCheckBox101.setEnabled(false);
        jPanel2.add(jCheckBox101);

        jCheckBox102.setEnabled(false);
        jPanel2.add(jCheckBox102);

        jCheckBox103.setEnabled(false);
        jPanel2.add(jCheckBox103);

        jCheckBox104.setEnabled(false);
        jPanel2.add(jCheckBox104);

        jCheckBox105.setEnabled(false);
        jPanel2.add(jCheckBox105);

        jCheckBox106.setEnabled(false);
        jPanel2.add(jCheckBox106);

        jCheckBox107.setEnabled(false);
        jPanel2.add(jCheckBox107);

        jCheckBox108.setEnabled(false);
        jPanel2.add(jCheckBox108);

        jCheckBox109.setEnabled(false);
        jPanel2.add(jCheckBox109);

        jCheckBox110.setSelected(true);
        jCheckBox110.setEnabled(false);
        jPanel2.add(jCheckBox110);

        jCheckBox111.setSelected(true);
        jCheckBox111.setEnabled(false);
        jPanel2.add(jCheckBox111);

        jCheckBox112.setSelected(true);
        jCheckBox112.setEnabled(false);
        jPanel2.add(jCheckBox112);

        jCheckBox113.setSelected(true);
        jCheckBox113.setEnabled(false);
        jPanel2.add(jCheckBox113);

        jCheckBox114.setSelected(true);
        jCheckBox114.setEnabled(false);
        jPanel2.add(jCheckBox114);

        jCheckBox115.setSelected(true);
        jCheckBox115.setEnabled(false);
        jPanel2.add(jCheckBox115);

        jCheckBox116.setSelected(true);
        jCheckBox116.setEnabled(false);
        jPanel2.add(jCheckBox116);

        jCheckBox117.setSelected(true);
        jCheckBox117.setEnabled(false);
        jPanel2.add(jCheckBox117);

        jCheckBox118.setSelected(true);
        jCheckBox118.setEnabled(false);
        jPanel2.add(jCheckBox118);

        jCheckBox119.setEnabled(false);
        jPanel2.add(jCheckBox119);

        jCheckBox120.setEnabled(false);
        jPanel2.add(jCheckBox120);

        jCheckBox121.setEnabled(false);
        jPanel2.add(jCheckBox121);

        jCheckBox122.setSelected(true);
        jCheckBox122.setEnabled(false);
        jPanel2.add(jCheckBox122);

        jCheckBox123.setSelected(true);
        jCheckBox123.setEnabled(false);
        jPanel2.add(jCheckBox123);

        jCheckBox124.setSelected(true);
        jCheckBox124.setEnabled(false);
        jPanel2.add(jCheckBox124);

        jCheckBox125.setSelected(true);
        jCheckBox125.setEnabled(false);
        jPanel2.add(jCheckBox125);

        jCheckBox126.setSelected(true);
        jCheckBox126.setEnabled(false);
        jPanel2.add(jCheckBox126);

        jCheckBox127.setSelected(true);
        jCheckBox127.setEnabled(false);
        jPanel2.add(jCheckBox127);

        jCheckBox128.setSelected(true);
        jCheckBox128.setEnabled(false);
        jPanel2.add(jCheckBox128);

        jCheckBox129.setSelected(true);
        jCheckBox129.setEnabled(false);
        jPanel2.add(jCheckBox129);

        jCheckBox130.setSelected(true);
        jCheckBox130.setEnabled(false);
        jPanel2.add(jCheckBox130);

        jCheckBox131.setSelected(true);
        jCheckBox131.setEnabled(false);
        jPanel2.add(jCheckBox131);

        jCheckBox132.setSelected(true);
        jCheckBox132.setEnabled(false);
        jPanel2.add(jCheckBox132);

        jCheckBox133.setSelected(true);
        jCheckBox133.setEnabled(false);
        jPanel2.add(jCheckBox133);

        jCheckBox134.setSelected(true);
        jCheckBox134.setEnabled(false);
        jPanel2.add(jCheckBox134);

        jCheckBox135.setSelected(true);
        jCheckBox135.setEnabled(false);
        jPanel2.add(jCheckBox135);

        jCheckBox136.setSelected(true);
        jCheckBox136.setEnabled(false);
        jPanel2.add(jCheckBox136);

        jCheckBox137.setSelected(true);
        jCheckBox137.setEnabled(false);
        jPanel2.add(jCheckBox137);

        jCheckBox138.setSelected(true);
        jCheckBox138.setEnabled(false);
        jPanel2.add(jCheckBox138);

        jCheckBox139.setSelected(true);
        jCheckBox139.setEnabled(false);
        jPanel2.add(jCheckBox139);

        jCheckBox140.setSelected(true);
        jCheckBox140.setEnabled(false);
        jPanel2.add(jCheckBox140);

        jCheckBox141.setSelected(true);
        jCheckBox141.setEnabled(false);
        jPanel2.add(jCheckBox141);

        jCheckBox142.setSelected(true);
        jCheckBox142.setEnabled(false);
        jPanel2.add(jCheckBox142);

        jCheckBox143.setSelected(true);
        jCheckBox143.setEnabled(false);
        jPanel2.add(jCheckBox143);

        jCheckBox144.setSelected(true);
        jCheckBox144.setEnabled(false);
        jPanel2.add(jCheckBox144);

        jCheckBox145.setSelected(true);
        jCheckBox145.setEnabled(false);
        jPanel2.add(jCheckBox145);

        jCheckBox146.setSelected(true);
        jCheckBox146.setEnabled(false);
        jPanel2.add(jCheckBox146);

        jCheckBox147.setEnabled(false);
        jPanel2.add(jCheckBox147);

        jCheckBox148.setSelected(true);
        jCheckBox148.setEnabled(false);
        jPanel2.add(jCheckBox148);

        jCheckBox149.setSelected(true);
        jCheckBox149.setEnabled(false);
        jPanel2.add(jCheckBox149);

        jCheckBox150.setEnabled(false);
        jPanel2.add(jCheckBox150);

        jCheckBox151.setEnabled(false);
        jPanel2.add(jCheckBox151);

        jCheckBox152.setSelected(true);
        jCheckBox152.setEnabled(false);
        jPanel2.add(jCheckBox152);

        jCheckBox153.setSelected(true);
        jCheckBox153.setEnabled(false);
        jPanel2.add(jCheckBox153);

        jCheckBox154.setSelected(true);
        jCheckBox154.setEnabled(false);
        jPanel2.add(jCheckBox154);

        jCheckBox155.setEnabled(false);
        jPanel2.add(jCheckBox155);

        jCheckBox156.setEnabled(false);
        jPanel2.add(jCheckBox156);

        jCheckBox157.setSelected(true);
        jCheckBox157.setEnabled(false);
        jPanel2.add(jCheckBox157);

        jCheckBox158.setSelected(true);
        jCheckBox158.setEnabled(false);
        jPanel2.add(jCheckBox158);

        jCheckBox159.setSelected(true);
        jCheckBox159.setEnabled(false);
        jPanel2.add(jCheckBox159);

        jCheckBox160.setSelected(true);
        jCheckBox160.setEnabled(false);
        jPanel2.add(jCheckBox160);

        jCheckBox161.setSelected(true);
        jCheckBox161.setEnabled(false);
        jPanel2.add(jCheckBox161);

        jCheckBox162.setSelected(true);
        jCheckBox162.setEnabled(false);
        jPanel2.add(jCheckBox162);

        jCheckBox163.setSelected(true);
        jCheckBox163.setEnabled(false);
        jPanel2.add(jCheckBox163);

        jCheckBox164.setSelected(true);
        jCheckBox164.setEnabled(false);
        jPanel2.add(jCheckBox164);

        jCheckBox165.setSelected(true);
        jCheckBox165.setEnabled(false);
        jPanel2.add(jCheckBox165);

        jCheckBox166.setSelected(true);
        jCheckBox166.setEnabled(false);
        jPanel2.add(jCheckBox166);

        jCheckBox167.setSelected(true);
        jCheckBox167.setEnabled(false);
        jPanel2.add(jCheckBox167);

        jCheckBox168.setSelected(true);
        jCheckBox168.setEnabled(false);
        jPanel2.add(jCheckBox168);

        jCheckBox169.setSelected(true);
        jCheckBox169.setEnabled(false);
        jPanel2.add(jCheckBox169);

        jCheckBox170.setSelected(true);
        jCheckBox170.setEnabled(false);
        jPanel2.add(jCheckBox170);

        jCheckBox171.setSelected(true);
        jCheckBox171.setEnabled(false);
        jPanel2.add(jCheckBox171);

        jCheckBox172.setSelected(true);
        jCheckBox172.setEnabled(false);
        jPanel2.add(jCheckBox172);

        jPanel3.setLayout(new java.awt.GridLayout(9, 1, 1, 1));

        jTextField12.setText("Alarcon Taboada Luis");
        jPanel3.add(jTextField12);

        jTextField13.setText("Araujo Lucas Giovanna");
        jPanel3.add(jTextField13);

        jTextField14.setText("Bastidas Angeles Jonathan");
        jPanel3.add(jTextField14);

        jTextField15.setText("Carreño Valerio Wilder");
        jPanel3.add(jTextField15);

        jTextField16.setText("Quintana Solorzano");
        jPanel3.add(jTextField16);

        jTextField17.setForeground(new java.awt.Color(255, 51, 51));
        jTextField17.setText("Morales Meneses");
        jPanel3.add(jTextField17);

        jTextField18.setText("Vargas Bajonero Ricky");
        jPanel3.add(jTextField18);

        jTextField19.setText("Quineche Carreño Moises");
        jPanel3.add(jTextField19);

        jTextField20.setText("Castillo Pardo Mayra");
        jPanel3.add(jTextField20);

        jPanel4.setLayout(new java.awt.GridLayout(10, 0, 0, 1));

        jLabel1.setText("Total");
        jPanel4.add(jLabel1);

        jLabel2.setText("18/18");
        jPanel4.add(jLabel2);

        jLabel3.setText("15/18");
        jPanel4.add(jLabel3);

        jLabel6.setText("15/18");
        jPanel4.add(jLabel6);

        jLabel4.setText("16/18");
        jPanel4.add(jLabel4);

        jLabel8.setText("15/18");
        jPanel4.add(jLabel8);

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("9/18");
        jPanel4.add(jLabel9);

        jLabel13.setText("15/18");
        jPanel4.add(jLabel13);

        jLabel11.setText("15/18");
        jPanel4.add(jLabel11);

        jLabel5.setText("16/18");
        jPanel4.add(jLabel5);

        jPanel5.setLayout(new java.awt.GridLayout(10, 0, 0, 1));

        jLabel7.setText("Porcentaje Inasistencia");
        jPanel5.add(jLabel7);

        jLabel15.setText("0%");
        jPanel5.add(jLabel15);

        jLabel16.setText("16.6%");
        jPanel5.add(jLabel16);

        jLabel17.setText("16.6%");
        jPanel5.add(jLabel17);

        jLabel18.setText("11.11%");
        jPanel5.add(jLabel18);

        jLabel19.setText("16.6%");
        jPanel5.add(jLabel19);

        jLabel20.setForeground(new java.awt.Color(255, 51, 51));
        jLabel20.setText("50%");
        jPanel5.add(jLabel20);

        jLabel21.setText("16.6%");
        jPanel5.add(jLabel21);

        jLabel37.setText("16.6%");
        jPanel5.add(jLabel37);

        jLabel38.setText("11.11%");
        jPanel5.add(jLabel38);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Tiempo del Sistema:"));

        jTextField84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField84.setText("09");

        jTextField152.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField152.setText("32");

        jTextField153.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField153.setText("13");

        jLabel39.setText("h");

        jLabel40.setText("m");

        jLabel41.setText("s");

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel42.setText("Lunes 15 Marzo 2009");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/playClock.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel43))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField152, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField153, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(jTextField152, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(jTextField153, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel44.setText("Escuela:");

        jLabel45.setText("Curso:");

        jLabel46.setText("Ciclo:");

        jLabel47.setText("Ingeniería Informática");

        jLabel48.setText("VII");

        jLabel49.setText("Marketing Estrátegico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(jLabel47))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel49))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox100;
    private javax.swing.JCheckBox jCheckBox101;
    private javax.swing.JCheckBox jCheckBox102;
    private javax.swing.JCheckBox jCheckBox103;
    private javax.swing.JCheckBox jCheckBox104;
    private javax.swing.JCheckBox jCheckBox105;
    private javax.swing.JCheckBox jCheckBox106;
    private javax.swing.JCheckBox jCheckBox107;
    private javax.swing.JCheckBox jCheckBox108;
    private javax.swing.JCheckBox jCheckBox109;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox110;
    private javax.swing.JCheckBox jCheckBox111;
    private javax.swing.JCheckBox jCheckBox112;
    private javax.swing.JCheckBox jCheckBox113;
    private javax.swing.JCheckBox jCheckBox114;
    private javax.swing.JCheckBox jCheckBox115;
    private javax.swing.JCheckBox jCheckBox116;
    private javax.swing.JCheckBox jCheckBox117;
    private javax.swing.JCheckBox jCheckBox118;
    private javax.swing.JCheckBox jCheckBox119;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox120;
    private javax.swing.JCheckBox jCheckBox121;
    private javax.swing.JCheckBox jCheckBox122;
    private javax.swing.JCheckBox jCheckBox123;
    private javax.swing.JCheckBox jCheckBox124;
    private javax.swing.JCheckBox jCheckBox125;
    private javax.swing.JCheckBox jCheckBox126;
    private javax.swing.JCheckBox jCheckBox127;
    private javax.swing.JCheckBox jCheckBox128;
    private javax.swing.JCheckBox jCheckBox129;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox130;
    private javax.swing.JCheckBox jCheckBox131;
    private javax.swing.JCheckBox jCheckBox132;
    private javax.swing.JCheckBox jCheckBox133;
    private javax.swing.JCheckBox jCheckBox134;
    private javax.swing.JCheckBox jCheckBox135;
    private javax.swing.JCheckBox jCheckBox136;
    private javax.swing.JCheckBox jCheckBox137;
    private javax.swing.JCheckBox jCheckBox138;
    private javax.swing.JCheckBox jCheckBox139;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox140;
    private javax.swing.JCheckBox jCheckBox141;
    private javax.swing.JCheckBox jCheckBox142;
    private javax.swing.JCheckBox jCheckBox143;
    private javax.swing.JCheckBox jCheckBox144;
    private javax.swing.JCheckBox jCheckBox145;
    private javax.swing.JCheckBox jCheckBox146;
    private javax.swing.JCheckBox jCheckBox147;
    private javax.swing.JCheckBox jCheckBox148;
    private javax.swing.JCheckBox jCheckBox149;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox150;
    private javax.swing.JCheckBox jCheckBox151;
    private javax.swing.JCheckBox jCheckBox152;
    private javax.swing.JCheckBox jCheckBox153;
    private javax.swing.JCheckBox jCheckBox154;
    private javax.swing.JCheckBox jCheckBox155;
    private javax.swing.JCheckBox jCheckBox156;
    private javax.swing.JCheckBox jCheckBox157;
    private javax.swing.JCheckBox jCheckBox158;
    private javax.swing.JCheckBox jCheckBox159;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox160;
    private javax.swing.JCheckBox jCheckBox161;
    private javax.swing.JCheckBox jCheckBox162;
    private javax.swing.JCheckBox jCheckBox163;
    private javax.swing.JCheckBox jCheckBox164;
    private javax.swing.JCheckBox jCheckBox165;
    private javax.swing.JCheckBox jCheckBox166;
    private javax.swing.JCheckBox jCheckBox167;
    private javax.swing.JCheckBox jCheckBox168;
    private javax.swing.JCheckBox jCheckBox169;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox170;
    private javax.swing.JCheckBox jCheckBox171;
    private javax.swing.JCheckBox jCheckBox172;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox80;
    private javax.swing.JCheckBox jCheckBox81;
    private javax.swing.JCheckBox jCheckBox82;
    private javax.swing.JCheckBox jCheckBox83;
    private javax.swing.JCheckBox jCheckBox84;
    private javax.swing.JCheckBox jCheckBox85;
    private javax.swing.JCheckBox jCheckBox86;
    private javax.swing.JCheckBox jCheckBox87;
    private javax.swing.JCheckBox jCheckBox88;
    private javax.swing.JCheckBox jCheckBox89;
    private javax.swing.JCheckBox jCheckBox90;
    private javax.swing.JCheckBox jCheckBox91;
    private javax.swing.JCheckBox jCheckBox92;
    private javax.swing.JCheckBox jCheckBox93;
    private javax.swing.JCheckBox jCheckBox94;
    private javax.swing.JCheckBox jCheckBox95;
    private javax.swing.JCheckBox jCheckBox96;
    private javax.swing.JCheckBox jCheckBox97;
    private javax.swing.JCheckBox jCheckBox98;
    private javax.swing.JCheckBox jCheckBox99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField152;
    private javax.swing.JTextField jTextField153;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField84;
    // End of variables declaration//GEN-END:variables

}
