/*
 * JPanelNoticia.java
 *
 * Created on 27 de febrero de 2008, 11:51 AM
 */

package cooperacionmisc;

/**
 *
 * @author  Administrado
 */
public class JPanelNoticia extends javax.swing.JPanel {
    
    /** Creates new form JPanelNoticia */
    public JPanelNoticia() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabelTituloNot = new javax.swing.JLabel();
        jLabelFechaAutor = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonLeerMas = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(142, 172, 187), 1, true));
        jLabelTituloNot.setBackground(new java.awt.Color(198, 226, 255));
        jLabelTituloNot.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelTituloNot.setText("\u00bb Clasificatoria Abierta Liga Xtreme 2008");
        jLabelTituloNot.setOpaque(true);

        jLabelFechaAutor.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFechaAutor.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabelFechaAutor.setText("Feb 19, 2008 - 7:48 PM - por NoobZaibot ");
        jLabelFechaAutor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jLabelFechaAutor.setOpaque(true);

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\Administrado\\Escritorio\\bannerbloodzone.jpg"));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 10));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Clasificatoria Abierta Liga Xtreme 2008 ( CALX 2008 ), que no es otra cosa que la puerta al evento central del gaming peruano : La Liga Peruana de Ciberdeportes Xtreme.\n\nEl sitio web ya esta ONLINE : http://calx.ligaxtreme.com ! \n\nComo bien saben, la Liga Xtreme consta de 10 equipos los cuales en su primera temporada fueron invitados. Ahora, al terminar la Liga, dos equipos \"bajaran\" por asi decirlo al llano, y dos equipos subiran a la primera ");
        jScrollPane1.setViewportView(jTextArea1);

        jButtonLeerMas.setText("Leer M\u00e1s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTituloNot, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
            .addComponent(jLabelFechaAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonLeerMas))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTituloNot, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLeerMas))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeerMas;
    private javax.swing.JLabel jLabelFechaAutor;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelTituloNot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
