/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IDE.java
 *
 * Created on 27-dic-2009, 14:22:28
 */

package Gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import storedprocedure.StoredProcedure;
import table.Table;

/**
 *
 * @author VAN BASTEM
 */
public class IDE extends javax.swing.JDialog {

    /** Creates new form IDE */
    private String nametable="";
    private JPopupMenu popupCreateSP=new JPopupMenu();
    private JMenuItem itemProcedure=new JMenuItem(" Create Procedure ");
    private JPopupMenu popupExecute=new JPopupMenu();
    private JMenuItem itemSentencia=new JMenuItem(" Execute Procedure ");


    public IDE(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTables();
        setProcedures();
        itemProcedure.setIcon(new ImageIcon(this.getClass().getResource("/images/procedure.png")));
        itemProcedure.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              mostrar();
            }
        });
       popupCreateSP.add(itemProcedure);

        itemSentencia.setIcon(new ImageIcon(this.getClass().getResource("/images/execute.png")));
        itemSentencia.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              executeProcedure();
            }
        });
       popupExecute.add(itemSentencia);

       this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

    }


    public void setTables(){
        ArrayList<Table> data= StoredProcedure.readTables();
        DefaultTableModel dt=(DefaultTableModel) jtName.getModel();
        for(Table da:data)
            dt.addRow(new Object[]{da.getTable()});
    }

     public void setProcedures(){
        refrescarTableProcedure();
        ArrayList<String> data= StoredProcedure.getProcedure();
        DefaultTableModel dti=(DefaultTableModel) jTable2.getModel();
        for(String da:data)
            dti.addRow(new Object[]{da.toString()});
    }

     public void refrescarTableProcedure(){

          DefaultTableModel dt=(DefaultTableModel) jTable2.getModel();
          int cantRow=jTable2.getRowCount();
          for(int i=0;i<cantRow;i++){
              dt.removeRow(0);
          }

     }
    public void mostrar(){
        Operaciones f= new Operaciones(this, true);
        f.setTable(nametable);
        f.setLocationRelativeTo(this);
        f.setVisible(true);
        jTextArea1.setText(f.getScript());
        StoredProcedure.getProcedure();

    }

    public void executeProcedure(){

        String rpta=StoredProcedure.executeProcedure(this.jTextArea1.getText());
       if(rpta==null){
           JOptionPane.showMessageDialog(jTextArea1,"Procedimiento creado con Exito ..!");
         setProcedures();}
       else
           JOptionPane.showMessageDialog(jTextArea1, rpta);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtName = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jtName.setAutoCreateRowSorter(true);
        jtName.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Table"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtName.setShowHorizontalLines(false);
        jtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtNameMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtName);
        jtName.getColumnModel().getColumn(0).setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea1MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stored Procedure"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Step:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("1º   Seleccionar una Tabla.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("2º   Dar Click Derecho sobre la Tabla.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("3º     Para Ejecutar los procedimiento almacenados hacer click derecho sobre el Area de Texto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(136, 136, 136)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNameMouseReleased

        try{
        int row=jtName.getSelectedRow();
        nametable=String.valueOf(jtName.getValueAt(row,0));
         if(evt.isPopupTrigger()){
            jtName.clearSelection();
            popupCreateSP.show(jtName, evt.getX(), evt.getY());
            itemProcedure.setText("Create procedure "+nametable);
        }
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(jTextArea1,"Debe selecionar una Tabla, antes de Hacer Click Derecho ..");
        }catch(IndexOutOfBoundsException ex){

        }
}//GEN-LAST:event_jtNameMouseReleased

    private void jTextArea1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseReleased
      try{
         if(jTextArea1.getText().trim().length()==0)
                return;
         if(evt.isPopupTrigger()){            
            popupExecute.show(jtName, evt.getX(), evt.getY());
           
        }
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(jTextArea1,"Debe selecionar una Tabla, antes de Hacer Click Derecho ..");
        }catch(IndexOutOfBoundsException ex){

        }


    }//GEN-LAST:event_jTextArea1MouseReleased

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IDE dialog = new IDE(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable jtName;
    // End of variables declaration//GEN-END:variables

}
