/*
 * CellDetail.java
 *
 * Created on November 23, 2008, 8:58 PM
 */
package admin.live;

import admin.live.LiveMonitor;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author  rCuser
 */
public class CellDetail extends javax.swing.JPanel {

    public static Color myGray = new Color(241, 240, 240);
    ImageIcon icon = new ImageIcon(getClass().getResource("/img/checkmark.png"));
    static Cursor handCursor = new Cursor(Cursor.HAND_CURSOR);
    int tries = 0;

    /** Creates new form CellDetail */
    public CellDetail() {
        initComponents();
        this.setPreferredSize(new Dimension(LiveMonitor.WIDTHCELL, LiveMonitor.HEIGHTCELL));
    }

    public void setDefault() {
        labTime.setText("");
        labState.setText(" --");
        if (getMouseListeners().length == 1) {
            removeMouseListener(getMouseListeners()[0]);
        }
    }
    boolean solved = false;

    public void setSolved(String time) {
        labTime.setText(time);
        if (!solved) {
            solved = true;
            labState.setIcon(icon);
            setCursor(handCursor);
        }
    }

    public void setUnsolved() {
        if (solved) {
            labState.setText(" --");
            labState.setIcon(null);
            solved = false;
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    public void setGray() {
        setBackground(myGray);
        labTime.setBackground(myGray);
        labState.setBackground(myGray);
        labTries.setBackground(myGray);
    }

    public void setTries(int t) {
        if (t > 0) {
            if (t != tries) {
                if (t == 1) {
                    labTries.setText(t + " intento fallido");
                } else {
                    labTries.setText(t + " intentos fallidos");
                }
            }
        } else {
            labTries.setText("");
        }
        this.tries = t;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labState = new javax.swing.JLabel();
        labTime = new javax.swing.JLabel();
        labTries = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        labState.setBackground(new java.awt.Color(255, 255, 255));
        labState.setOpaque(true);
        labState.setPreferredSize(new java.awt.Dimension(16, 16));
        add(labState, new java.awt.GridBagConstraints());

        labTime.setBackground(new java.awt.Color(255, 255, 255));
        labTime.setFont(new java.awt.Font("Tahoma", 1, 12));
        labTime.setForeground(new java.awt.Color(51, 153, 0));
        labTime.setOpaque(true);
        labTime.setPreferredSize(new java.awt.Dimension(57, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(labTime, gridBagConstraints);

        labTries.setBackground(new java.awt.Color(255, 255, 255));
        labTries.setFont(new java.awt.Font("Arial", 0, 11));
        labTries.setOpaque(true);
        labTries.setPreferredSize(new java.awt.Dimension(90, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        add(labTries, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labState;
    private javax.swing.JLabel labTime;
    private javax.swing.JLabel labTries;
    // End of variables declaration//GEN-END:variables
}
