/*
 * PanTiempoReset.java
 *
 * Created on December 1, 2008, 2:52 PM
 */
package admin.live;

import admin.Concurso;
import admin.ServidorConcurso;
import java.awt.Dimension;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class PanTiempoReset extends javax.swing.JPanel {

    private ServidorConcurso servidor;
    //
    private PanTimeSetting panTimeSetting;
    JDialog dialog;
    private JFrame owner;

    public PanTiempoReset(ServidorConcurso servidor, JFrame owner) {
        this.servidor = servidor;
        this.owner = owner;        
        initComponents();
        initMyComponents();
        setEstadoInicial();
    }

    private void initMyComponents() {
        long totalTime = servidor.concurso.getTotalTime();
        long leftTime = servidor.concurso.getLeftTime();
        labConcursoName.setText(servidor.concurso.getNombre());
        
        dialog = new JDialog(owner, "Time Settings");
        dialog.setModal(true);

        panTimeSetting = new PanTimeSetting(totalTime, leftTime, dialog);
        Dimension msise = new Dimension(400, 250);
        dialog.setPreferredSize(msise);
        dialog.setSize(msise);
        dialog.add(panTimeSetting);
        RCContainer.centerFrame(dialog);
//        dialog.set
        dialog.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosed(WindowEvent e) {
                panTimeSetting.ok = false;
            }
        });

        labDuracion.setText(RCUtil.longToTime(totalTime));
        labLeftTime.setText(RCUtil.longToTime(leftTime));
    }

    class TimeFormatListener implements ChangeListener {

        public void stateChanged(ChangeEvent e) {
            JSpinner spin = (JSpinner) e.getSource();
            if (Integer.parseInt(spin.getModel().getPreviousValue() + "") < 0) {
                spin.setValue(0);
            }
            if (Integer.parseInt(spin.getModel().getNextValue() + "") > 60) {
                spin.setValue(60);
            }
        }
    }

    void setEstadoInicial() {
        butEstablecerTiempo.setEnabled(true);
        butComenzar.setEnabled(false);
        butComenzar.setText("GoGoGo");
        butFinalizar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butComenzar = new javax.swing.JButton();
        butEstablecerTiempo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labLeftTime = new javax.swing.JLabel();
        chkAutoStop = new javax.swing.JCheckBox();
        butFinalizar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labDuraCap = new javax.swing.JLabel();
        labDuracion = new javax.swing.JLabel();
        labConcursoName = new javax.swing.JLabel();

        butComenzar.setText("GoGoGo");
        butComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butComenzarActionPerformed(evt);
            }
        });

        butEstablecerTiempo.setText("Tiempos");
        butEstablecerTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEstablecerTiempoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setText("Tiempo Restante:");

        labLeftTime.setFont(new java.awt.Font("Tahoma", 1, 24));
        labLeftTime.setText("00:00:00");

        chkAutoStop.setSelected(true);
        chkAutoStop.setText("AutoStop");

        butFinalizar.setText("Stop");
        butFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFinalizarActionPerformed(evt);
            }
        });

        jButton2.setText("L");

        labDuraCap.setText("Duración:");

        labDuracion.setText("00:00:00");

        labConcursoName.setFont(new java.awt.Font("Verdana", 1, 18));
        labConcursoName.setText("Concurso Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(butEstablecerTiempo)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labConcursoName, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkAutoStop)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labLeftTime, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(butComenzar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butFinalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labDuraCap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labDuracion)
                        .addContainerGap(384, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAutoStop)
                    .addComponent(labConcursoName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butEstablecerTiempo)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDuraCap)
                    .addComponent(labDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butFinalizar)
                    .addComponent(butComenzar)
                    .addComponent(jLabel1)
                    .addComponent(labLeftTime)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void butEstablecerTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEstablecerTiempoActionPerformed
        long totalTime = servidor.concurso.getTotalTime();
        long leftTime = servidor.concurso.getLeftTime();
        dialog.setVisible(true);

        if (panTimeSetting.ok) {
            totalTime = panTimeSetting.getTotalTime();
            leftTime = panTimeSetting.getLeftTime();
            servidor.setTimes(totalTime, leftTime);
            labDuracion.setText(RCUtil.longToTime(totalTime));
            labLeftTime.setText(RCUtil.longToTime(leftTime));
            butComenzar.setEnabled(true);
        } else {
        }
}//GEN-LAST:event_butEstablecerTiempoActionPerformed

    private void butComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butComenzarActionPerformed
        if (butComenzar.getText().equals("GoGoGo")) {
            servidor.comenzarConcurso(labLeftTime, chkAutoStop);
            butComenzar.setText("Pausar");
            butFinalizar.setEnabled(true);
            butEstablecerTiempo.setEnabled(false);
        } else if (butComenzar.getText().equals("Pausar")) {
            servidor.pause();
            butComenzar.setText("Resumir");
        } else if (butComenzar.getText().equals("Reanudar")) {
            servidor.resume(labLeftTime, chkAutoStop);
            butComenzar.setText("Pausar");
        }
    }//GEN-LAST:event_butComenzarActionPerformed

    private void butFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFinalizarActionPerformed
        servidor.finalizarConcurso();
        setEstadoInicial();
    }//GEN-LAST:event_butFinalizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton butComenzar;
    public javax.swing.JButton butEstablecerTiempo;
    private javax.swing.JButton butFinalizar;
    private javax.swing.JCheckBox chkAutoStop;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labConcursoName;
    private javax.swing.JLabel labDuraCap;
    private javax.swing.JLabel labDuracion;
    public javax.swing.JLabel labLeftTime;
    // End of variables declaration//GEN-END:variables
}
