
import cecocadb.DB;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import rclib.RCContainer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanInexistentes.java
 *
 * Created on Feb 7, 2009, 9:20:46 PM
 */
/**
 *
 * @author rCuser
 */
public class PanCodiPostInexistentes extends javax.swing.JPanel {

    /** Creates new form PanInexistentes */
    private Validacion validacion;
    private DB database;
    private int id_concurso;
    private JTable tableHIs;

    public PanCodiPostInexistentes(DB database, int id_concurso) {
        this.database = database;
        this.id_concurso = id_concurso;
        initComponents();
        initMyComponents();
    }

    public boolean calculate() throws SQLException {
        boolean ok = false;
        Object[] results = null;
        ok = (Boolean) results[0];
        if ((Boolean) results[0]) {
            labEstado.setText("Passed Inexistentes test");
        } else {
            labEstado.setText("Failed Inexistentes test");
            ArrayList<String[]> reg = (ArrayList<String[]>) results[1];
            String[][] data = (String[][]) (reg.toArray(new String[0][]));
            String[] columnNames = {"Correlativo", "codi_postulante Inexistente", "litocodigo"};
            tableHIs = new JTable(new HITableModel(data, columnNames));
            spaneInexistentes.setViewportView(tableHIs);
            setVisible(false);
            setVisible(true);
        }
        return ok;
    }

    private void initMyComponents() {
        validacion = new Validacion(database);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        spaneInexistentes = new javax.swing.JScrollPane();
        labEstado = new javax.swing.JLabel();

        jButton1.setText("Run!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        spaneInexistentes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true), "Inexistentes"));

        labEstado.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaneInexistentes, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(labEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(spaneInexistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            calculate();
        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(PanCodiPostInexistentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labEstado;
    private javax.swing.JScrollPane spaneInexistentes;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) throws SQLException {
        DB database = new DB();
        RCContainer.showPanel(new PanCodiPostInexistentes(database, 1));
//        database.closeDB();
    }
}
